### ISSUE TITLE
Invalid certificate

### ISSUE THREAD

**Issue by dreammonkey** [sfx101/deck#1]
Hi,

I started using this app a while ago, I'm wondering is it still under active development ?
The certificate used to serve the stacks seems to have expired.

Is it possible to change the domain/certificate the stacks are running on ?

Thanks

**Comment by sfx101** [comment]
Hi @dreammonkey sorry about that, we were actively working on a windows version and were planning to release a revamped version of both Mac and Windows this month. 
But I will patch the certificate error and create a release version by today or early tomorrow morning. 
Thanks!

**Comment by dreammonkey** [comment]
That's awesome, thanks !

**Comment by sfx101** [comment]
Hi @dreammonkey , please download the latest release of the app here https://github.com/sfx101/docker-stacks/releases

That should fix the cert issue
