### ISSUE TITLE
Slash in GET is rewrited to backslash

### ISSUE THREAD

**Issue by stanaSulc** [sfx101/deck#109]
I create new LAMP app and created simple php file to just read GET and here is result. 
Am I doing something wrong? I have clean Win11 install and clean DECK install this is first project I created
![image](https://user-images.githubusercontent.com/107994938/195576776-8499a4e8-bccc-48e7-8503-d974e95bbe7e.png)

**Comment by nabad600** [comment]
Hi @stanaSulc, 
Thank you for using DECK, 
We understand your issue, can you please access "non secure" URL `(i.e. http://127.0.0.1:<portnumber>/?route=abc/abc )` and revert back

![image](https://user-images.githubusercontent.com/67466982/195578900-061def9c-2380-4751-abb9-bf352232dc0b.png)

we'd be happy to help.

**Comment by nabad600** [comment]
Hi @stanaSulc,
We may need to close this ticket in the next 24 hours. So, I request you to inform us about the status of your query.
Let us know of any issues, we'd be happy to help.
