### ISSUE TITLE
How to uninstall everything

### ISSUE THREAD

**Issue by tvaughan73** [sfx101/deck#114]
Something has messed up with my deck install and I want to do a clean install.  Other than uninstalling the deck app in Windows how do I uninstall everything else including the WSL deck-app server?

**Comment by nabad600** [comment]
Hi @tvaughan73, 
Thank you for using DECK, as your requirement below mention details
## Uninstall or remove apps and programs in Windows
### **Windows 11**
![image](https://user-images.githubusercontent.com/67466982/201240913-6940fb5f-2d3e-4a11-8b48-e10c82aa87df.png)
### **Windows 10**
![image](https://user-images.githubusercontent.com/67466982/201241064-9c6ec1cf-24c9-4fe7-8076-ede585934d9a.png)
## Uninstall or remove DECK from WSL 

1. Open Start.
2. Search for Command Prompt, right-click the top result, and select the Run as administrator option.
3. Type the following command to view a list of all available distros and press Enter:
`wsl -l -v`
4. Type the following command to set a distro as the new default and press Enter:
`wsl --unregister DISTRO-NAME`
In the command, replace DISTRO-NAME for the name of the distro
For example, this command unregisters and deletes the DECK Linux distribution:
`wsl --unregister deck-app`
 
Let us know of any issues, we'd be happy to help.
