### ISSUE TITLE
mySQL container not working on deck app & docker

### ISSUE THREAD

**Issue by CamKem** [sfx101/deck#115]
Hi again,

I am having an issue with using mySQL on the deck app.

I can see (as in the screenshots) that in both the deck app & docker the containers are not running.
I tried starting the mysql container on both the deck app & docker desktop and it didn't work.

I tried restarting both the docker & and deck apps with no luck.

I am not aware of the path to the mysql container so I cant add it into the path list as it recommends

Thanks in advance for your assistance.

![20221111 104748 1](https://user-images.githubusercontent.com/112100521/201334973-4fce318b-a9e5-4613-a471-60cc4f8370c4.jpeg)
![20221111 104806 1](https://user-images.githubusercontent.com/112100521/201334990-3558479c-3b8e-422f-bdf4-fba48420ec82.jpeg)

**Comment by nabad600** [comment]
Hi @CamKem,

Thank you for using DECK, can you share MAC OS version and system architecture?

**Comment by CamKem** [comment]
![20221112 092851 1](https://user-images.githubusercontent.com/112100521/201470030-70a5a5eb-d592-4414-80ca-e9aaca9b9743.jpeg)

**Comment by nabad600** [comment]
Hello, @CamKem
We appreciate you giving this information, and MySQL is working fine. Please establish a fresh MySQL stack by erasing all MySQL containers and images. I really hope it works.
<img width="1514" alt="image" src="https://user-images.githubusercontent.com/67466982/201587411-249576d7-2083-48c1-9ec5-10ba40e5693a.png">
<img width="1271" alt="image (1)" src="https://user-images.githubusercontent.com/67466982/201587428-56a80cdb-b0e6-40af-aa71-2f1f680a2050.png">

Please verify "Disk Image Location" in your "Docker Desktop," as noted.
![Screenshot 2022-11-14 at 11 37 42 AM](https://user-images.githubusercontent.com/67466982/201587692-c380fd55-8635-44fe-b93e-be1ebe5a7981.png)

**Comment by nabad600** [comment]
Hi @CamKem 
We may need to close this ticket in the next 24 hours. So, I request you to inform us about the status of your query.
Let us know of any issues, we'd be happy to help.
