### ISSUE TITLE
No README or invalid url GITHUB for create a project

### ISSUE THREAD

**Issue by martin-lechene** [sfx101/deck#120]
Holà, 

![deck_1](https://user-images.githubusercontent.com/46826871/207063114-7dbca9ce-44f1-49ef-938e-bcb761ea1ceb.png)
![deck_2](https://user-images.githubusercontent.com/46826871/207063115-885eb4b6-13f0-43ce-a1fd-4e6314efdc01.png)
The problem occurred after deleting a project I had just created, since then, even after a complete reinstallation... 
And after 30 minutes, the problem was solved by reinstalling as admin + opening the software in admin mode, do the rest of the installation and wait 5 minutes. 
(I predict no worries about connection or networks) 
![deck_3-afteradmin](https://user-images.githubusercontent.com/46826871/207063309-86236628-6a0b-4eb0-9000-71d5ae298087.png)

**Comment by nabad600** [comment]
Hi @martin-lechene Thank you for the report.
We used it repeatedly without figuring out the reporting issue. make sure your host system has internet.
It appears to be a network-related problem.
Thanks

**Comment by raymonkiller** [comment]
good

**Comment by nabad600** [comment]
Hi @martin-lechene 
We may need to close this ticket in the next 24 hours. So, I request you to inform us about the status of your query.
Let us know of any issues, we'd be happy to help.

**Comment by martin-lechene** [comment]
Hi @nabad600, No problem. 
The problem didn't persist and although I retried the manipulations that had led to this. The ticket can be closed.
