### ISSUE TITLE
Can not create Laravel stack on macOS

### ISSUE THREAD

**Issue by C10ne** [sfx101/deck#22]
I'm on macOS Big Sur v11.2.3.

Downloaded dmg file and installed v3.0.0 of the app.
.docker-stacks directory is created in my ~.
I select Laravel to add to deck, fill in the info and click "Save and deploy".
"Configure and deploy stack" modal stays open, the button is disabled, but nothing else happens.
Directory named as project is created in ~/.docker-stacks/apps.
~/.docker-stacks/stacks.json contains only empty array.
Screenshots are provided.

<img width="1270" alt="Screenshot 2021-04-03 at 00 54 58" src="https://user-images.githubusercontent.com/724726/113459961-6b486f80-9417-11eb-81b6-f087358e4783.png">
<img width="1270" alt="Screenshot 2021-04-03 at 00 55 11" src="https://user-images.githubusercontent.com/724726/113459964-6d123300-9417-11eb-87a3-089e701e6531.png">
<img width="1270" alt="Screenshot 2021-04-03 at 00 55 50" src="https://user-images.githubusercontent.com/724726/113459966-6e436000-9417-11eb-8ad0-59ca1a103d66.png">
<img width="1270" alt="Screenshot 2021-04-03 at 00 55 55" src="https://user-images.githubusercontent.com/724726/113459967-6edbf680-9417-11eb-8c9d-389b99a1cc37.png">
<img width="586" alt="Screenshot 2021-04-03 at 00 57 40" src="https://user-images.githubusercontent.com/724726/113460033-a054c200-9417-11eb-9592-9935cf2ed5ee.png">

**Comment by C10ne** [comment]
I can create LEMP stack, but can't run it.
The error is:


```
Building nginx
[+] Building 1.2s (4/4) FINISHED                                                                                        
 => [internal] load build definition from Dockerfile-7.4                                                           0.0s
 => => transferring dockerfile: 3.12kB                                                                             0.0s
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => ERROR [internal] load metadata for docker.io/library/alpine:3.9                                                1.1s
 => [auth] library/alpine:pull token for registry-1.docker.io                                                      0.0s
------
 > [internal] load metadata for docker.io/library/alpine:3.9:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to authorize: rpc error: code = Unknown desc = failed to fetch oauth token: unexpected status: 401 Unauthorized
ERROR: Service 'nginx' failed to build
```

Docker desktop is at latest version.

```
docker -v
Docker version 20.10.5, build 55c4c88
```

**Comment by sfx101** [comment]
Hi @C10ne , the Laravel issue is resolved. Could you please try once again from your end? Thank you for reporting.
