### ISSUE TITLE
Proxy server converting slashes in query parameters

### ISSUE THREAD

**Issue by baileyherbert** [sfx101/deck#24]
Hi! 👋

I just started messing around with this on a new Windows 11 setup and quickly ran into an issue with the proxy server. When using stacks.run any forward slashes (`/`) in query parameters somehow get converted to backslashes (`\\`). As a result, phpMyAdmin is throwing 404s all over the place. When I connect directly to the container port this doesn't happen.

**stacks.run –**
```
"POST /index.php?route=\\config\\get HTTP/1.1" 404
"POST /index.php?route=\\navigation&ajax_request=1 HTTP/1.1" 404
"POST /index.php?route=\\config\\get HTTP/1.1" 404
```

**localhost –**
```
"POST /index.php?route=/config/get HTTP/1.1" 200
"POST /index.php?route=/navigation&ajax_request=1 HTTP/1.1" 200
"POST /index.php?route=/config/get HTTP/1.1" 200
```

Perhaps a configuration issue on my part or just a case of accidentally using `path.sep` in the wrong place?

**Comment by nabad600** [comment]
Hi @baileyherbert thank you for trying out & reporting the bug, Issue is resolved

![image](https://user-images.githubusercontent.com/67466982/172546766-ad430003-ca81-4e6f-b2e4-1687f5a2ada0.png)

Let us know of any issues, we'd be happy to help.
