### ISSUE TITLE
Domain stacks.run not running 

### ISSUE THREAD

**Issue by keyser69** [sfx101/deck#31]
Hello,
i'm new to Deck. 

I just downloaded v3.0 on my MacOS Monterey and installed Docker and Deck following your documentation. I'm now running both Docker and Deck and i'm pulling some images for testing.

I'm trying Wordpress and LAMP. They install correctly, i can reach projects and services (phpmyadmin and mysql) with localhost:port address but i can't reach them with stacks.run domain.

I have Deck listening on port 80 and 443 (see attachment).

Maybe am i missing something on installation or configuration ?

<img width="662" alt="Schermata 2021-11-03 alle 20 04 16" src="https://user-images.githubusercontent.com/1038307/140176269-4e5c2195-f779-42ad-8476-1ec0e791152c.png">

**Comment by sfx101** [comment]
Hi, @keyser69 what error do you get when you open the stacks.run domain? Does it just say unreachable or respond with an error?

**Comment by keyser69** [comment]
It just says host is unreachable.

**Comment by kto32** [comment]
I want to join this problem, the stacks.run domain doesn't start for me either, I'm trying to run on windows 10, wsl2, Alpine linux, docker desktop
![image](https://user-images.githubusercontent.com/56291605/146839018-bc2f6c12-2e90-4c1a-a7d4-cbd834bfcadc.png)
![image](https://user-images.githubusercontent.com/56291605/146839272-015c6011-d128-4541-abf9-e52c6249b511.png)

**Comment by aadilayub** [comment]
Encountered the same error trying to run a wordpress stack for the first time in Ubuntu

**Comment by nabad600** [comment]
Hi @aadilayub, please reinstall DECK using the installer.sh script. and it's work
![image](https://user-images.githubusercontent.com/67466982/172545026-f7db5366-026f-4ee5-b2c7-5dd373bca3b9.png)
Appreciate your feedback here. Let us know of any issues, we'd be happy to help.
