### ISSUE TITLE
Expired Certificate - DECK v3.0.0 on MacOS 

### ISSUE THREAD

**Issue by eriku** [sfx101/deck#33]
![Screen Shot 2021-12-06 at 8 01 41 AM](https://user-images.githubusercontent.com/1197769/144859425-b35d1ebf-4f36-4c62-b2db-707a709e0904.jpg)

**Comment by sfx101** [comment]
Hi @eriku , the latest certificates have been updated. 
Please restart the app & try again.
Some browsers might have an old cert in the cache, so please open in incognito or private more to test.
