### ISSUE TITLE
[REQUEST] Add Solidity stack

### ISSUE THREAD

**Issue by Juan-de-Costa-Rica** [sfx101/deck#34]
Hey, love deck, been using it for all my php stuff. Starting to get into some Ethereum stuff now, is it possible to have a Solidity stack?

**Comment by sfx101** [comment]
Hi @Juan-de-Costa-Rica , awesome. Glad to hear it. 
Yes, of course. We'll add Solidity stack to the marketplace and let you know by next week.

**Comment by Juan-de-Costa-Rica** [comment]
@sfx101 any update on this? I see there is a Solidity repo in the deck-app org, but I don't see it in the Deck Marketplace. Thanks
