### ISSUE TITLE
Support for non-Debian Linux

### ISSUE THREAD

**Issue by aadilayub** [sfx101/deck#40]
I want to try out this app, but unfortunately I can't since I use Fedora Linux. It'd be great if Deck was installable via an AppImage or Flatpak instead just as a .deb package, which only works on Debian and Ubuntu based distributions.

**Comment by sfx101** [comment]
Hi @aadilayub we'll be maintaining Ubuntu for 2022. However, we do have plans to have support for other distros in the future.

**Comment by asjur** [comment]
> Hi @aadilayub we'll be maintaining Ubuntu for 2022. However, we do have plans to have support for other distros in the future.

Any update for this? An AppImage would be great.
