### ISSUE TITLE
Shell is working weirdly.

### ISSUE THREAD

**Issue by artemismars** [sfx101/deck#42]
Hi, I found this project in `Dev.to`!

and I started using Deck app! It looks neat.
and I am trying to use `Nodejs shell` in the app. but I found this bug.
When I open the Node Shell via Deck app, the focus is placed inappropriately (the issue is the image below)

![image](https://user-images.githubusercontent.com/75290655/158176705-7a871f01-5e61-471d-8c74-26367c8b5e9c.png)

**Comment by nebula-byte** [comment]
Hi, @artemismars thanks for trying out DECK.
For windows, we will be releasing V4 in the next two weeks. The new version fixes terminal UI issues. We will keep you posted. Ty.

**Comment by artemismars** [comment]
@nebula-byte Thanks for your effort. I will wait for the version! :)
