### ISSUE TITLE
[REQUEST] Custom Images

### ISSUE THREAD

**Issue by alexevladgabriel** [sfx101/deck#44]
Ability to have your own custom images, ability to import into DECK your own application and create it like you want.

**Comment by sfx101** [comment]
Hi @alexevladgabriel please check this repo https://github.com/deck-app/custom-stack
It has instructions for adding custom stacks to DECK, any docker-compose project can be imported.
Let me know if you need any help, would be happy to assist

**Comment by eriku** [comment]
@sfx101 - Thank you so much for building DECK! I did try and create a custom stack but I can't seem to get it to show in the marketplace (followed the steps in your documentation).

This is my `~/.deck/storage/custom-stacks.json`
