### ISSUE TITLE
LAMP Stack with PHP 8.1

### ISSUE THREAD

**Issue by grandeljay** [sfx101/deck#48]
Hello,

I just installed DECK, it looks awesome, thanks for making this! I just set up a LAMP stack but can only select PHP up to 8, but my project requires PHP 8.1, how do I add or select it?

Thanks!

Best
Jay

**Comment by sfx101** [comment]
Hi @grandeljay I am glad you found it useful. We are working on releasing 8.1 very shortly (by next week or so). You'll receive it automatically  and be able to select version 8.1 in the UI once we release. Will keep you posted here.

**Comment by eriku** [comment]
@sfx101 - Any word on when you'll be releasing PHP 8.1? (BTW v4 is a HUGE upgrade, thanks for building DECK!)

**Comment by nabad600** [comment]
Hi @grandeljay, php 8.1 release, Let us know for any issues, we'd be happy to help.
