### ISSUE TITLE
Not work in MacOS

### ISSUE THREAD

**Issue by keynertyc** [sfx101/deck#5]
I'm in MacOS Catalina V.10.15.7 . I downloaded and installed Deck V.2.0.0 and gave it permission in preferences. After open the Application I can't do anything, no option works, all blank.

![Screen Shot 2020-11-11 at 16 46 41](https://user-images.githubusercontent.com/1308334/98868021-805b3c80-243d-11eb-9fd1-d957ac86c0da.png)

**Comment by sfx101** [comment]
Hi @keynertyc 

Please try this

`cd ~ && mkdir .docker-stacks && cd .docker-stacks && git clone https://github.com/sfx101/docker-stacks.git .`

The above should have been done automatically by the app but it didn't happen in your case, the command would create a data folder in your home dir and clone the repo for storing configurations

Once done, please restart the app

**Comment by keynertyc** [comment]
Thank you so much. It's working.
