### ISSUE TITLE
[Request] Appwrite

### ISSUE THREAD

**Issue by 99hats** [sfx101/deck#50]
Wow guys, I'm really loving your platform. So much nicer than dealing with Docker desktops and ngrok.

I think you have a really great window of opportunity here getting Appwrite working on Deck.

https://dev.to/devteam/announcing-the-appwrite-hackathon-on-dev-1oc0

Best,
Kevin

**Comment by nabad600** [comment]
HI @99hats, Thanks for your feedback. 
We may need to close this ticket in the next 24 hours. So, I request you to inform us about the status of your query.
Let us know of any issues, we'd be happy to help.
