### ISSUE TITLE
[Request] Iris

### ISSUE THREAD

**Issue by kataras** [sfx101/deck#51]
Hello,

I would love to see [Iris](https://github.com/kataras/iris) integration to DECK as well. I can help.

**Comment by sfx101** [comment]
Hi, @kataras awesome! If you can provide the Docker image I can add it to the in-app marketplace.
Or you could also follow this document https://github.com/sfx101/deck/blob/master/CONTRIBUTING.md to create a PR for this repo. Please use the branch `deck-v4`

**Comment by nabad600** [comment]
Hi @kataras, Iris has been added,
![Screenshot 2022-06-17 at 4 45 40 PM](https://user-images.githubusercontent.com/67466982/174289622-da968bc9-d95f-4ef2-8416-621f78493c1c.png)
![Screenshot 2022-06-17 at 4 47 58 PM](https://user-images.githubusercontent.com/67466982/174289650-a6dd2bb1-135f-41ea-8a13-89023165de9f.png)

Let us know of any issues, we'd be happy to help.
