### ISSUE TITLE
Laravel Development Container does not include Node.js and npm

### ISSUE THREAD

**Issue by Kyzegs** [sfx101/deck#58]
The Development Container for Laravel does not include Node.js and npm. Two essential parts to get everything working within the Laravel ecosystem.

**Comment by sfx101** [comment]
Hi @Kyzegs Node & npm have been added to the laravel container. Appreciate your feedback here.

**Comment by Kyzegs** [comment]
I just tried a fresh Laravel installation, and it does not include Node.js and npm. I don't see any updates to the [repository](https://github.com/deck-app/laravel) either.

**Comment by abir1984** [comment]
Hi @Kyzegs,

You can delete old docker image. I hope it's work.
