### ISSUE TITLE
Laravel Development Container does not include any database installations

### ISSUE THREAD

**Issue by Kyzegs** [sfx101/deck#59]
The Laravel Development Container allows you to pick from a variety of PHP extensions, including database drivers. So why is it that we cannot install a database itself? We should be able to pick a database installation to go alongside our application.

**Comment by Subhajit9836** [comment]
Hi @Kyzegs 

We decided to not attach the databases with Laravel Dev Container as it'll trim down the size of the image DECK is requesting. Everyone doesn't use databases with Laravel and we didn't want to limit the users to one type of database management system. We have various database images like MySQL, MongoDB, or Oracle in DECK. One can install any of them and connect to Laravel when required. Thanks!

**Comment by Kyzegs** [comment]
I've tried connecting to the database with the given information. It always results in the following error:

```
SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known
```

I've tried with the following provided information:

![image](https://user-images.githubusercontent.com/45851377/172646235-8b90a715-bcf4-4b54-9ceb-4c2e1fe8449a.png)
