### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by dbateson** [sfx101/deck#60]
<img width="483" alt="Screenshot 2022-06-07 at 11 45 42" src="https://user-images.githubusercontent.com/2852537/172350314-434513e2-5e23-4481-aa9e-8e4ec790ed1e.png">

**Comment by Subhajit9836** [comment]
Hi @dbateson 

We have fixed the issue and you won't see the expired cert anymore. Thanks for informing us about the issue upfront.
