### ISSUE TITLE
Slash in PHP variables are transformed to backslash

### ISSUE THREAD

**Issue by Scorpio256** [sfx101/deck#64]
Hi, I'm trying to install opencart but all the routes are broken because they are replaced / on \
I'm trying on my project also on clean from the stack but the error is the same. 
I tried to find a solution but it's beyond me.

**Comment by Scorpio256** [comment]
I try check phpmyadmin container and looks like this container work fine. When I try $_GET variable at phpmyadmin output is fine. On opencart or LAMP all slash are changed.

**Comment by nabad600** [comment]
Hi, @Scorpio256, we are review the code, every thing fine, we are not maintenance opencart project. Appreciate your feedback here.

**Comment by Scorpio256** [comment]
This problém is not on opencart only, same in LAMP just dump $_GET in simple index a try write slash
