### ISSUE TITLE
Support for other Linux distros

### ISSUE THREAD

**Issue by Parables** [sfx101/deck#73]
In #43, support was requested for Fedora.

What needs to be done to support other distros?

How can I contribute?

I am thinking of a Universal package like an AppImage or a Snap package.

How do we get this done ASAP?

**Comment by nabad600** [comment]
Hi @Parables, we're doing R&D to support Fedora and other Linux distributions very soon. I will keep you posted on the progress. and it's a duplicate ticket, so close this ticket.
