### ISSUE TITLE
Output console window does not expand

### ISSUE THREAD

**Issue by batv45** [sfx101/deck#78]
![image](https://user-images.githubusercontent.com/32638802/189438762-f6d2add6-1291-4d73-a3ff-971109d07b2b.png)

![image](https://user-images.githubusercontent.com/32638802/189438882-3b79b319-300b-406c-902f-1df6f6a64070.png)

**Comment by nabad600** [comment]
Hi @batv45,
Thank you for your feedback, Now it's resolved the issue, please find the below mention snapshot

![image](https://user-images.githubusercontent.com/67466982/224235269-9a2feba5-3f4d-4888-9a50-1e61b1061af2.png)

Let us know of any issues, we'd be happy to help.
