### ISSUE TITLE
Grant Full Disk Access to "nfsd"

### ISSUE THREAD

**Issue by Houbsi** [sfx101/deck#80]
Hi there,

i followed these instructions:

![Bildschirm­foto 2022-09-18 um 13 05 29](https://user-images.githubusercontent.com/70960/190898948-badd126b-7bdc-4500-b689-bfdce93552ae.png)

I restarted my macOS system but still no luck. This comes every time i want to save a new Project.

**Comment by presswizards** [comment]
Same: Grant Full Disk Access to "nfsd" keeps coming up even after already adding it to Full Disk Access. I've restarted Deck, rebooted, etc. Mac Studio M1 Max on Monterey 12.6 with Deck 4.2.0.

**Comment by sfx101** [comment]
Hi,

Please try the fix in the comment and see if it still has this issue https://github.com/sfx101/deck/issues/85#issuecomment-1250705676

**Comment by Houbsi** [comment]
@sfx101 Yes! :) That did the trick!

Multipass shows an update for me. Is it safe to update it? Or does Deck take care of that to?
