### ISSUE TITLE
No Connection could be made because the target machine refused it

### ISSUE THREAD

**Issue by iamlasse** [sfx101/deck#82]
I've just installed Deck on a Windows 11 laptop and tried starting a new project and this error is preventing any start.
I saw a closed issue with the same problem but my WSL is not including the deck-app 

NAME                   STATE           VERSION
* docker-desktop         Running         2      
  docker-desktop-data    Running         2      
  Ubuntu-18.04           Stopped         2   

but looks like this instead.

Any help appreciated.

**Comment by nabad600** [comment]
Hi @iamlasse, thanks for reporting.

Could you please do the following?

 1. If you use "Docker Desktop", open the deck app and go to setting, click on Docker engine & uncheck Remote engine
 
![image](https://user-images.githubusercontent.com/67466982/191013577-61b410b2-eca1-4b1a-9d34-5dbde7b3defc.png)

also remove "DOCKER_HOST" from environment variables
![image](https://user-images.githubusercontent.com/67466982/191014433-ecdbbd39-e0e7-43a2-ba84-75639cb74741.png)


2. If you use `wsl with virtual host`, then do the following?
    a. Uninstall `docker decktop` and deleted `` c:/users/<user name>/.deck``
    b. open the deck app and go to setting, click on Docker engine & uncheck Remote engine
    ![image](https://user-images.githubusercontent.com/67466982/191013577-61b410b2-eca1-4b1a-9d34-5dbde7b3defc.png)
    
    reopen `deck` app and installation page should appear. Below is the screenshot for your reference
    ![image](https://user-images.githubusercontent.com/67466982/191015275-138a9950-674e-44e5-b758-a7ab8a8d91e2.png)
    
     Please verify `deck-app` virtual host created or not
     ![image](https://user-images.githubusercontent.com/67466982/191015513-3ef94dea-fb6e-4525-ae93-45b7f1d3d3c1.png)

Appreciate your feedback here.
