### ISSUE TITLE
Trying to install on Mac OS Catalina "deck-app"

### ISSUE THREAD

**Issue by mircobabini** [sfx101/deck#83]
> exec failed: instance "deck-app" is not running

**Comment by sfx101** [comment]
Hi @mircobabini could you please try this? https://github.com/sfx101/deck/issues/85#issuecomment-1250705676

**Comment by mircobabini** [comment]
1. Can't open the app and change the settings, because it's stuck in the installing window.
2. Uninstalled multipass and everything via shell
3. Re-run the install procedure:

```
echo -e '\x1bc' && sh /Applications/DECK.app/Contents/Resources/scripts/installer.sh /Applications/DECK.app/Contents/Resources/multipass/multipass.pkg ; exit
xit
x1bc
Installing multipass, this will take a few secs ...
Password:
installer: Package name is multipass
installer: Installing at base path /
installer: The install was successful.
ca7747dfcae5ee948ffee4c81099b1a4
Creating a lightweight Ubuntu VM, this will take a few mins ...
launch failed: The following errors occurred:                                   
Instance stopped while starting
30cc5285d6bc297b9ca633042957def0                                                
exec failed: instance "deck-app" is not running
```

Any alternative to change that setting?

**Comment by Subhajit9836** [comment]
Hi @mircobabini 

I'm closing this ticket as you created a separate ticket with a new issue.

Thanks

**Comment by mircobabini** [comment]
**@Subhajit9836 this ticket must say open.**

The new ticket is related to another mac.
#83 is the issue I'm having on My macOs Catalina (computer 1)
#88 is the issue I'm having on my macOS Monterey (computer 2)

These are two completely different machines.
