### ISSUE TITLE
Symfony will not install

### ISSUE THREAD

**Issue by tvaughan73** [sfx101/deck#84]
This is on Windows.  See screenshot of error below.

![image](https://user-images.githubusercontent.com/850122/190924298-3102fc04-c93b-4216-8cd4-12e29b4c89dc.png)

**Comment by Subhajit9836** [comment]
Hi @tvaughan73 

We've fixed the issue with Symphony. Tested it thoroughly on our side. Can you please check and get back to us if you still see the issue or not?

Thanks

**Comment by Subhajit9836** [comment]
Hi @tvaughan73 

Please send us an update related to the issue you faced with Symphony. Otherwise, we may need to close this ticket in next 48 hours.

Thanks

**Comment by tvaughan73** [comment]
Thanks, I was able to get it installed.

**Comment by Subhajit9836** [comment]
Thanks, @tvaughan73. I'm closing this ticket then. Have a good day.
