### ISSUE TITLE
docker-credential-desktop": executable file not found in $PATH

### ISSUE THREAD

**Issue by Houbsi** [sfx101/deck#86]
After i fixed issue #80 

I'm getting now the following error right after i want to start my Laravel Project:

`1 error occurred:
        * error listing credentials - err: exec: "docker-credential-desktop": executable file not found in $PATH, out: ``
`
My settings:

![Bildschirm­foto 2022-09-19 um 10 59 47](https://user-images.githubusercontent.com/70960/190983488-6393988f-5971-471b-a4f9-7e7e2fa68c9a.png)

Docker Desktop or anything else is not installed anymore.

**Comment by sfx101** [comment]
Please run this, `rm -rf ~/.docker`
It removes the docker desktop config files in home directory

**Comment by Houbsi** [comment]
@sfx101 Thanks.

I used the --uninstall for Dockere and used Appcleaner.. But this, i forgot to check.
