### ISSUE TITLE
Stuck on "Grant Full Disk Access to nfsd"

### ISSUE THREAD

**Issue by mircobabini** [sfx101/deck#88]
I installed everything smoothly on macOS Monterey.

Trying to install my first app but I'm stuck on that screen.
1) Granted full disk access to nfsd following the same exact steps in the modal guide
2) Rebooted my system

**Comment by nabad600** [comment]
Hi @mircobabini, 
Please can you run and share output.
`multipass version`, `multipass list` and `multipass exec deck-app -- cat /etc/auto.projects`

**Comment by mircobabini** [comment]
```
mircobabini@juice ~ % multipass version
multipass   1.8.1+mac
multipassd  1.8.1+mac
mircobabini@juice ~ % multipass list
Name                    State             IPv4             Image
deck-app                Running           192.168.64.2     Ubuntu 20.04 LTS
                                          172.18.0.1
                                          172.17.0.1
mircobabini@juice ~ % multipass exec deck-app -- cat /etc/auto.projects
/home/ubuntu/mircobabini -fstype=nfs,rw,nolock,nosuid,proto=tcp,resvport 192.168.0.107:/Users/mircobabini
mircobabini@juice ~ %
```

**Comment by nabad600** [comment]
Hi @mircobabini, 
Thanks for your reply, please review the installation process.

https://www.loom.com/share/94f1a2d0d8734916938c8ab113454fe2
Appreciate your feedback here.

**Comment by mircobabini** [comment]
I see that you keep suggesting me and other people (https://github.com/sfx101/deck/issues/85#issuecomment-1251516556) to review the installation process and the set up of the Full Grant Access.

Trust me: we know what we are doing and we are doing it the right way. **Something is buggy here**. And probably the Docker Remote/Local Engine is involved. I've experienced similar behaviours like @presswizards reported.

Had to activate Local docker to get everything working here. The exact steps I've done:
1) Un-check the Remote Engine option
2) Run the uninstall.sh
3) Reopen Dock and go through the install procedure once again
4) Now my sites are working

Please note that after this procedure the Remote Engine is still CHECKED, even if I had unchecked it as reported above (1st bullet). Once again: **it's buggy**.

Also, please re-open ticket https://github.com/sfx101/deck/issues/83 which is for a completely different issue (or maybe something related, but still not fixed on that Catalina env.)

**If you want to investigate on my environment to check the issues by yourself, I'm glad to give you an access to run experiments. Feel free to contact me.**

**Comment by sfx101** [comment]
Hi @mircobabini, let us try replicating the issue on our end. The reason @nabad600 is suggesting you to re-install is because he is unable to replicate it yet. And, tysm for your time and offering your environment to investigate, will reach out to you if we cannot replicate it in our systems.

**Comment by Subhajit9836** [comment]
Hi @mircobabini 

I've sent you an email to id mentioned in your github profile. The email is regarding these issues you are facing. Please check and reply to this email at your convenient time.

Thanks

**Comment by wpsumo** [comment]
Facing the same issue on the arm installation

**Comment by LeoSeyers** [comment]
was facing the same issue on apple silicon but @mircobabini steps helped fixed the issue

**Comment by nabad600** [comment]
Hi, 
We may need to close this ticket in the next 24 hours. So, I request you to inform us about the status of your query.
Let us know of any issues, we'd be happy to help.
