### ISSUE TITLE
wp-cli is missing in shell

### ISSUE THREAD

**Issue by mircobabini** [sfx101/deck#90]
Hey,

Is it possible to add wp-cli to the docker compose setup of a WordPress project?

**Comment by sfx101** [comment]
Yeah, of course. The stacks are docker compose projects so you can add anything.
Here's the WP image DECK uses: https://github.com/deck-app/wordpress
If you can add it yourself, feel free to create a PR on that repo, once it's merged it will available in the app or please give us a few days to add it, ty.

**Comment by mircobabini** [comment]
Cool, but I've no experience at all with docker compose.

Can just leave a few starting points:
- https://mklasen.com/adding-and-using-wp-cli-in-a-docker-compose-setup/
- https://gist.github.com/drdogbot7/cc7787540c1b4c925d383149e91fdf9f

**Comment by nabad600** [comment]
Hi @mircobabini, 

WP-cli has been added of a WordPress project.
![image](https://user-images.githubusercontent.com/67466982/192248897-eefe8d7b-7e02-43e7-a837-99fb76a6dd54.png)

Let us know of any issues, we'd be happy to help.
