### ISSUE TITLE
Grant Full Disk Access to "nfsd" bug

### ISSUE THREAD

**Issue by wpsumo** [sfx101/deck#91]
Grant Full Disk Access to "nfsd" but still getting the pop up and cannot proceed when installing wordpress project.

Stuck and even during a restart of deck I face the same.

**Comment by Subhajit9836** [comment]
Hi @wpsumo 

We tried but couldn't recreate the issue on our side. The best possible way forward is to have a zoom/skype screen share call between you and our developers if it's okay with you. We may need to see the exact problem you're facing to understand it properly. 

Thanks

**Comment by wpsumo** [comment]
Right now I just stick to local by flywheel, I have granted all your software require but the popup to grant is still there. Reinstall doesn't solve the problem. Using the apple silicon app.
