### ISSUE TITLE
how i can uninstall your app in ubuntu

### ISSUE THREAD

**Issue by danyk4** [sfx101/deck#95]
HI
ubuntu 22.04
install without errors but when i click on icon it doesnt launch.
how can i unistall it?

**Comment by Subhajit9836** [comment]
Hi @danyk4 

Seems like there are multiple instances of the Deck app already running in the background. You may need to close the current instances, reboot the system and try to run the app again. 

Also, I'll try to send you the documentation/video on how to uninstall the application.

Thanks

**Comment by Subhajit9836** [comment]
Hi again @danyk4 

Here's the code to uninstall Deck -

sudo dpkg --purge deck

Please inform us if it worked for you or not.

Thanks

**Comment by danyk4** [comment]
Hi,

yes it works
thank you

**Comment by Subhajit9836** [comment]
Thanks for the reply @danyk4. I'm gonna close the ticket now.
