### ISSUE TITLE
Can't figure out how to work with file permissions

### ISSUE THREAD

**Issue by badabingbreda** [sfx101/deck#97]
I tried installing Deck under Windows 11 and WSL2, but I just can't figure out how to work with the file permissions. deck-app maps the \\wsl$ network drive so that I can access files directly. It appears to be working but there are some issues with it.
I can create a WordPress stack, run it and access it just as expected. Whenever I copy in files manually (plugin) though, the application is unable to remove them, warning me of permission errors. Plugins installed via upload in WordPress work fine though, obviously it gets unpacked using the correct permissions there.

Did extensive Googling for a fix, I was unable to find it. And if there is a solution/workaround, Adding it to the docs would certainly help to get people stick with Deck.

**Comment by Subhajit9836** [comment]
Hi @badabingbreda 

Sorry for the delayed response. We're trying to recreate the problem on our side. We found the issue and will send you info about fixing the issue as soon as possible.

Thanks

**Comment by Subhajit9836** [comment]
Hi again

We found a makeshift solution for this issue. We'll still be working to have a permanent solution for this. But, for now, you can do the following to be able to delete the plugin from the Wordpress plugin section -

1. Go to the installed app(Wordpress) dashboard in the Deck and open the shell from there to access Wordpress directory. (Please check the attached file image_2022_09_29T09_05_27_785Z.png)
2. Change the plugin's folder ownership to www-data using the commands mentioned in the attached screenshot - image_2022_09_29T09_07_13_278Z.png. The actual command is - chown -R www-data:www-data <plugin's folder name>

Feel free to reply to this ticket if you face any issues executing the aforesaid steps. 

Thanks


![image_2022_09_29T09_05_27_785Z](https://user-images.githubusercontent.com/106807053/193222096-0db7099b-deab-40af-88fc-3c4d17480d10.png)
![image_2022_09_29T09_07_13_278Z](https://user-images.githubusercontent.com/106807053/193222109-5cde660a-3074-4226-aa45-7c40fdba86a0.png)

**Comment by Subhajit9836** [comment]
hi @badabingbreda 

We fixed this bug in our latest WordPress image. You can try the new image in DECK and report to us if you face any issues. For now, I'm closing this ticket in here. Thanks for reporting the bug to us.
